user_agent: "fri-wier-DOMACI_NJOKI"

# The seed URL's that the crawler will use to seed the frontier.
initial_urls:
  - "https://www.gov.si/"
  - "http://evem.gov.si/"
  - "https://e-uprava.gov.si/"
  - "https://www.e-prostor.gov.si/"

number_of_workers: 4

# Path to the selected Firefox headless browser
driver_path: "downloader/geckodriver.exe"