user_agent: "fri-wier-DOMACI_NJOKI"

# The seed URL's that the crawler will use to seed the frontier.
initial_urls:
  - "https://www.gov.si/"
  - "http://evem.gov.si/"
  - "https://e-uprava.gov.si/"
  - "https://www.e-prostor.gov.si/"

number_of_workers: 4

# Path to the selected Firefox headless browser
driver_path: "downloader/geckodriver.exe"

# How many seconds the crawler should wait for page to load.
page_load_timeout: 5

# Whether we want our browser to run in headless mode or not.
headless: False

# How many seconds to wait between consecutive requests to the same server if
# "Crawl-Delay" option is not set in "robots.txt" for a specified page.
wait_between_consecutive_requests: 5

#database connection
database_host: "localhost"
database_user: "postgres"
database_password: "postgres"
database_name: "postgres"